### PR TITLE
fix: android build issues

### LINKED ISSUE #109: Possible documentation update: EXPO_USE_METRO_WORKSPACE_ROOT=1 to build
I was getting a 404 error for the expo-router and was only able to run the app after exporting EXPO_USE_METRO_WORKSPACE_ROOT=1 as per the monorepo instructions. 

Should this be added to the build instructions or added automatically in the package.json file?

### PR DESCRIPTION
**Pull request by TimoGlastra**
Some fixes for android buliding. also fixes #109

### CODE REVIEW

**Review by berendsliedrecht — APPROVED** [review]

File: apps/ausweis/src/constants.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ MIICeTCCAiCgAwIBAgIUB5E9QVZtmUYcDtCjKB/H3VQv72gwCgYIKoZIzj0EAwIwgYgxCzAJBgNVBAYT
 
 // https://funke.animo.id
 const animoFunkeRelyingPartyCertificate =
-  'MIIBAzCBq6ADAgECAhArxq0w60RTDK4WY9HzgcvBMAoGCCqGSM49BAMCMAAwIBcNNzAwMTAxMDAwMDAwWhgPMjI4NjExMjAxNzQ2NDBaMAAwOTATBgcqhkjOPQIBBggqhkjOPQMBBwMiAALcD1XzKepFxWMAOqV+ln1fybBt7DRO5CV0f9A6mRp2xaMlMCMwIQYDVR0RBBowGIYWaHR0cHM6Ly9mdW5rZS5hbmltby5pZDAKBggqhkjOPQQDAgNHADBEAiAfvGG6sqrvzIMWYpJB5VLloo9f51loYXSkKxJIOztlNwIgLLSvEl0Dmp5vtj2buZ2nXQ2RBKxiLbc5eYGeMeoUnjk='
+  'MIIBAzCBq6ADAgECAhAcowXbm2aJXPP7Am0/DqMGMAoGCCqGSM49BAMCMAAwIBcNNzAwMTAxMDAwMDAwWhgPMjI4NjExMjAxNzQ2NDBaMAAwOTATBgcqhkjOPQIBBggqhkjOPQMBBwMiAALcD1XzKepFxWMAOqV+ln1fybBt7DRO5CV0f9A6mRp2xaMlMCMwIQYDVR0RBBowGIYWaHR0cHM6Ly9mdW5rZS5hbmltby5pZDAKBggqhkjOPQQDAgNHADBEAiBd0afYRMKslUz1DooFge3Vk2ggZcwlSkTF750rfa7MjAIgGFPM9J6PvAXkvsxUdC1xCcyCQBBrOsLdwqCT4wzTmko='
```
Comment (TimoGlastra) [inline apps/ausweis/src/constants.ts:11]: it is now : MIIBBTCBq6ADAgECAhAar4TMiACrMSPwZ04DngKaMAoGCCqGSM49BAMCMAAwIBcNNzAwMTAxMDAwMDAwWhgPMjI4NjExMjAxNzQ2NDBaMAAwOTATBgcqhkjOPQIBBggqhkjOPQMBBwMiAALcD1XzKepFxWMAOqV+ln1fybBt7DRO5CV0f9A6mRp2xaMlMCMwIQYDVR0RBBowGIYWaHR0cHM6Ly9mdW5rZS5hbmltby5pZDAKBggqhkjOPQQDAgNJADBGAiEA1pSuByfgYpXmUjs+OGIJvqeHXCtTXiMxZDKe7bH7ySUCIQDyLR+EfdKPgj83FGUB9sERjfrCH9sH6QwI0TPAJSGicA==
